import type { ModelNodeDefinition } from '../types';

export const NODE_DEFINITIONS: Record<string, ModelNodeDefinition> = {
  'gpt-image-1-generate': {
    id: 'gpt-image-1-generate',
    displayName: 'GPT Image 1',
    category: 'image-gen',
    apiProvider: 'openai',
    apiEndpoint: '/v1/images/generations',
    envKeyName: 'OPENAI_API_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'gpt-image-1',
        options: [
          { label: 'GPT Image 1', value: 'gpt-image-1' },
          { label: 'GPT Image 1.5', value: 'gpt-image-1.5' },
          { label: 'GPT Image 1 Mini', value: 'gpt-image-1-mini' },
        ],
      },
      {
        key: 'size',
        label: 'Size',
        type: 'enum',
        required: false,
        default: 'auto',
        options: [
          { label: 'Auto', value: 'auto' },
          { label: '1024×1024', value: '1024x1024' },
          { label: '1536×1024', value: '1536x1024' },
          { label: '1024×1536', value: '1024x1536' },
        ],
      },
      {
        key: 'quality',
        label: 'Quality',
        type: 'enum',
        required: false,
        default: 'auto',
        options: [
          { label: 'Auto', value: 'auto' },
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
        ],
      },
      {
        key: 'n',
        label: 'Count',
        type: 'integer',
        required: false,
        default: 1,
        min: 1,
        max: 10,
      },
      {
        key: 'output_format',
        label: 'Format',
        type: 'enum',
        required: false,
        default: 'png',
        options: [
          { label: 'PNG', value: 'png' },
          { label: 'JPEG', value: 'jpeg' },
          { label: 'WebP', value: 'webp' },
        ],
      },
      {
        key: 'background',
        label: 'Background',
        type: 'enum',
        required: false,
        default: 'auto',
        options: [
          { label: 'Auto', value: 'auto' },
          { label: 'Transparent', value: 'transparent' },
          { label: 'Opaque', value: 'opaque' },
        ],
      },
    ],
  },

  'claude-chat': {
    id: 'claude-chat',
    displayName: 'Claude',
    category: 'text-gen',
    apiProvider: 'anthropic',
    apiEndpoint: '/v1/messages',
    envKeyName: 'ANTHROPIC_API_KEY',
    executionPattern: 'stream',
    inputPorts: [
      { id: 'messages', label: 'Messages', dataType: 'Text', required: true },
      { id: 'images', label: 'Images', dataType: 'Image', required: false, multiple: true },
    ],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'claude-sonnet-4-6',
        options: [
          { label: 'Claude Opus 4', value: 'claude-opus-4-20250514' },
          { label: 'Claude Sonnet 4.6', value: 'claude-sonnet-4-6' },
          { label: 'Claude Haiku 3.5', value: 'claude-haiku-3-5-20241022' },
        ],
      },
      {
        key: 'max_tokens',
        label: 'Max Tokens',
        type: 'integer',
        required: true,
        default: 4096,
        min: 1,
        max: 200000,
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'float',
        required: false,
        default: 1,
        min: 0,
        max: 1,
        step: 0.1,
      },
      {
        key: 'system',
        label: 'System Prompt',
        type: 'textarea',
        required: false,
        default: '',
        placeholder: 'System instructions...',
      },
      {
        key: 'top_p',
        label: 'Top P',
        type: 'float',
        required: false,
        min: 0,
        max: 1,
        step: 0.05,
        placeholder: 'Default',
      },
      {
        key: 'stop_sequences',
        label: 'Stop Sequences',
        type: 'string',
        required: false,
        placeholder: 'Comma-separated',
      },
      {
        key: 'extended_thinking',
        label: 'Extended Thinking',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'thinkingBudget',
        label: 'Thinking Budget',
        type: 'integer',
        required: false,
        placeholder: 'Default (min 1024)',
        min: 1024,
        max: 200000,
        condition: 'extended_thinking',
      },
    ],
  },

  'runway-gen4-turbo': {
    id: 'runway-gen4-turbo',
    displayName: 'Runway Gen-4 Turbo',
    category: 'video-gen',
    apiProvider: 'runway',
    apiEndpoint: '/v1/tasks',
    envKeyName: 'RUNWAY_API_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'gen4_turbo',
        options: [
          { label: 'Gen-4 Turbo', value: 'gen4_turbo' },
          { label: 'Gen-4', value: 'gen4' },
          { label: 'Gen-4 Aleph', value: 'gen4_aleph' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: 5,
        options: [
          { label: '5 seconds', value: 5 },
          { label: '10 seconds', value: 10 },
        ],
      },
      {
        key: 'ratio',
        label: 'Ratio',
        type: 'enum',
        required: false,
        default: '1280:720',
        options: [
          { label: '1280x720', value: '1280:720' },
          { label: '1584x672', value: '1584:672' },
          { label: '1104x832', value: '1104:832' },
          { label: '720x1280', value: '720:1280' },
          { label: '832x1104', value: '832:1104' },
          { label: '960x960', value: '960:960' },
        ],
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
        min: 0,
        max: 4294967295,
      },
    ],
  },

  'elevenlabs-tts': {
    id: 'elevenlabs-tts',
    displayName: 'ElevenLabs TTS',
    category: 'audio-gen',
    apiProvider: 'elevenlabs',
    apiEndpoint: '/v1/text-to-speech/{voice_id}',
    envKeyName: 'ELEVENLABS_API_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'audio', label: 'Audio', dataType: 'Audio', required: false },
    ],
    params: [
      {
        key: 'model_id',
        label: 'Model',
        type: 'enum',
        required: false,
        default: 'eleven_multilingual_v2',
        options: [
          { label: 'v3 (Highest)', value: 'elevenlabs_v3' },
          { label: 'Multilingual v2', value: 'eleven_multilingual_v2' },
          { label: 'Flash v2.5', value: 'eleven_flash_v2_5' },
        ],
      },
      {
        key: 'stability',
        label: 'Stability',
        type: 'float',
        required: false,
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: 'voice_id',
        label: 'Voice ID',
        type: 'string',
        required: false,
        default: '21m00Tcm4TlvDq8ikWAM',
        placeholder: 'Rachel (default)',
      },
      {
        key: 'similarity_boost',
        label: 'Similarity Boost',
        type: 'float',
        required: false,
        default: 0.75,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: 'style',
        label: 'Style',
        type: 'float',
        required: false,
        default: 0,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: 'speed',
        label: 'Speed',
        type: 'float',
        required: false,
        default: 1.0,
        min: 0.1,
        max: 4.0,
        step: 0.1,
      },
      {
        key: 'output_format',
        label: 'Output Format',
        type: 'enum',
        required: false,
        default: 'mp3_44100_128',
        options: [
          { label: 'MP3 44.1kHz', value: 'mp3_44100_128' },
          { label: 'MP3 22kHz', value: 'mp3_22050_32' },
          { label: 'PCM 16kHz', value: 'pcm_16000' },
          { label: 'PCM 24kHz', value: 'pcm_24000' },
          { label: 'PCM 44.1kHz', value: 'pcm_44100' },
        ],
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
    ],
  },

  'flux-1-1-ultra': {
    id: 'flux-1-1-ultra',
    displayName: 'FLUX 1.1 Ultra',
    category: 'image-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/flux-pro/v1.1-ultra',
    envKeyName: ['FAL_KEY', 'BFL_API_KEY'],
    executionPattern: 'sync',
    directKeyName: 'BFL_API_KEY',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'Image Guide', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [],
    sharedParams: [
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '21:9', value: '21:9' },
          { label: '16:9', value: '16:9' },
          { label: '4:3', value: '4:3' },
          { label: '3:2', value: '3:2' },
          { label: '1:1', value: '1:1' },
          { label: '2:3', value: '2:3' },
          { label: '3:4', value: '3:4' },
          { label: '9:16', value: '9:16' },
          { label: '9:21', value: '9:21' },
        ],
      },
      {
        key: 'num_images',
        label: 'Count',
        type: 'integer',
        required: false,
        default: 1,
        min: 1,
        max: 4,
      },
    ],
    directParams: [
      {
        key: 'raw',
        label: 'Raw (Natural Look)',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
    falParams: [
      {
        key: 'safety_tolerance',
        label: 'Safety Tolerance',
        type: 'enum',
        required: false,
        default: '2',
        options: [
          { label: '1 (Strict)', value: '1' },
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
          { label: '5', value: '5' },
          { label: '6 (Permissive)', value: '6' },
        ],
      },
      {
        key: 'enhance_prompt',
        label: 'Enhance Prompt',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'output_format',
        label: 'Format',
        type: 'enum',
        required: false,
        default: 'jpeg',
        options: [
          { label: 'JPEG', value: 'jpeg' },
          { label: 'PNG', value: 'png' },
        ],
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
      {
        key: 'image_prompt_strength',
        label: 'Image Influence',
        type: 'float',
        required: false,
        default: 0.1,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
  },

  'text-input': {
    id: 'text-input',
    displayName: 'Text Input',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'value',
        label: 'Text',
        type: 'textarea',
        required: true,
        default: '',
        placeholder: 'Enter text or prompt...',
      },
    ],
  },

  'image-input': {
    id: 'image-input',
    displayName: 'Image Input',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'filePath',
        label: 'File',
        type: 'file',
        required: true,
        default: '',
      },
    ],
  },

  'preview': {
    id: 'preview',
    displayName: 'Preview',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'input', label: 'Input', dataType: 'Any', required: true },
    ],
    outputPorts: [],
    params: [],
  },

  'combine-text': {
    id: 'combine-text',
    displayName: 'Combine Text',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'text1', label: 'Text 1', dataType: 'Text', required: true },
      { id: 'text2', label: 'Text 2', dataType: 'Text', required: false },
      { id: 'text3', label: 'Text 3', dataType: 'Text', required: false },
    ],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'separator',
        label: 'Separator',
        type: 'string',
        required: false,
        default: '\\n',
        placeholder: 'e.g. \\n or " | " or ", "',
      },
      {
        key: 'template',
        label: 'Template',
        type: 'textarea',
        required: false,
        default: '',
        placeholder: 'Optional: use {text1}, {text2}, {text3} placeholders',
      },
    ],
  },

  'router': {
    id: 'router',
    displayName: 'Router',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'input', label: 'Input', dataType: 'Any', required: true },
    ],
    outputPorts: [
      { id: 'out1', label: 'Out 1', dataType: 'Any', required: false },
      { id: 'out2', label: 'Out 2', dataType: 'Any', required: false },
      { id: 'out3', label: 'Out 3', dataType: 'Any', required: false },
    ],
    params: [],
  },

  'reroute': {
    id: 'reroute',
    displayName: 'Reroute',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'input', label: '', dataType: 'Any', required: true },
    ],
    outputPorts: [
      { id: 'output', label: '', dataType: 'Any', required: false },
    ],
    params: [],
  },

  'openrouter-universal': {
    id: 'openrouter-universal',
    displayName: 'OpenRouter',
    category: 'universal',
    apiProvider: 'openrouter',
    apiEndpoint: 'https://openrouter.ai/api/v1/chat/completions',
    envKeyName: 'OPENROUTER_API_KEY',
    executionPattern: 'stream',
    inputPorts: [
      { id: 'messages', label: 'Messages', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'string',
        required: true,
        default: '',
        placeholder: 'Loading models...',
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'float',
        required: false,
        default: 1.0,
        min: 0,
        max: 2,
        step: 0.1,
      },
      {
        key: 'max_tokens',
        label: 'Max Tokens',
        type: 'integer',
        required: false,
        default: 4096,
        min: 1,
        max: 200000,
      },
    ],
  },

  'replicate-universal': {
    id: 'replicate-universal',
    displayName: 'Replicate',
    category: 'universal',
    apiProvider: 'replicate',
    apiEndpoint: 'https://api.replicate.com/v1/predictions',
    envKeyName: 'REPLICATE_API_TOKEN',
    executionPattern: 'async-poll',
    inputPorts: [],
    outputPorts: [],
    params: [
      {
        key: 'model_id',
        label: 'Model ID',
        type: 'string',
        required: true,
        default: '',
        placeholder: 'owner/name (e.g. stability-ai/sdxl)',
      },
    ],
  },

  'fal-universal': {
    id: 'fal-universal',
    displayName: 'FAL',
    category: 'universal',
    apiProvider: 'fal',
    apiEndpoint: 'https://queue.fal.run',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
      { id: 'audio', label: 'Audio', dataType: 'Audio', required: false },
      { id: 'mesh', label: 'Mesh', dataType: 'Mesh', required: false },
    ],
    params: [
      {
        key: 'endpoint_id',
        label: 'Endpoint',
        type: 'string',
        required: true,
        default: 'fal-ai/flux-pro/v1.1-ultra',
        placeholder: 'fal-ai/flux-pro/v1.1-ultra',
      },
    ],
  },

  'dalle-3-generate': {
    id: 'dalle-3-generate',
    displayName: 'DALL-E 3',
    category: 'image-gen',
    apiProvider: 'openai',
    apiEndpoint: '/v1/images/generations',
    envKeyName: 'OPENAI_API_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'dall-e-3',
        options: [
          { label: 'DALL-E 3', value: 'dall-e-3' },
          { label: 'DALL-E 2', value: 'dall-e-2' },
        ],
      },
      {
        key: 'size',
        label: 'Size',
        type: 'enum',
        required: false,
        default: '1024x1024',
        options: [
          { label: '1024×1024', value: '1024x1024' },
          { label: '1024×1792', value: '1024x1792' },
          { label: '1792×1024', value: '1792x1024' },
        ],
      },
      {
        key: 'quality',
        label: 'Quality',
        type: 'enum',
        required: false,
        default: 'standard',
        options: [
          { label: 'Standard', value: 'standard' },
          { label: 'HD', value: 'hd' },
        ],
      },
      {
        key: 'style',
        label: 'Style',
        type: 'enum',
        required: false,
        default: 'vivid',
        options: [
          { label: 'Vivid', value: 'vivid' },
          { label: 'Natural', value: 'natural' },
        ],
      },
    ],
  },

  'gpt-4o-chat': {
    id: 'gpt-4o-chat',
    displayName: 'GPT-4o Chat',
    category: 'text-gen',
    apiProvider: 'openai',
    apiEndpoint: '/v1/chat/completions',
    envKeyName: 'OPENAI_API_KEY',
    executionPattern: 'stream',
    inputPorts: [
      { id: 'messages', label: 'Messages', dataType: 'Text', required: true },
      { id: 'images', label: 'Images', dataType: 'Image', required: false, multiple: true },
    ],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'gpt-4o',
        options: [
          { label: 'GPT-4o', value: 'gpt-4o' },
          { label: 'GPT-4o Mini', value: 'gpt-4o-mini' },
          { label: 'GPT-4.1', value: 'gpt-4.1' },
        ],
      },
      {
        key: 'max_tokens',
        label: 'Max Tokens',
        type: 'integer',
        required: false,
        default: 4096,
        min: 1,
        max: 128000,
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'float',
        required: false,
        default: 1,
        min: 0,
        max: 2,
        step: 0.1,
      },
      {
        key: 'top_p',
        label: 'Top P',
        type: 'float',
        required: false,
        min: 0,
        max: 1,
        step: 0.05,
        placeholder: 'Default',
      },
      {
        key: 'frequency_penalty',
        label: 'Frequency Penalty',
        type: 'float',
        required: false,
        default: 0,
        min: -2,
        max: 2,
        step: 0.1,
      },
      {
        key: 'presence_penalty',
        label: 'Presence Penalty',
        type: 'float',
        required: false,
        default: 0,
        min: -2,
        max: 2,
        step: 0.1,
      },
      {
        key: 'response_format',
        label: 'Response Format',
        type: 'enum',
        required: false,
        default: 'text',
        options: [
          { label: 'Text', value: 'text' },
          { label: 'JSON', value: 'json_object' },
        ],
      },
    ],
  },

  'gemini-chat': {
    id: 'gemini-chat',
    displayName: 'Gemini',
    category: 'text-gen',
    apiProvider: 'google',
    apiEndpoint: '/v1beta/models/{model}:streamGenerateContent',
    envKeyName: 'GOOGLE_API_KEY',
    executionPattern: 'stream',
    inputPorts: [
      { id: 'messages', label: 'Messages', dataType: 'Text', required: true },
      { id: 'images', label: 'Images', dataType: 'Image', required: false, multiple: true },
    ],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'gemini-2.5-flash',
        options: [
          { label: 'Gemini 3.1 Pro', value: 'gemini-3.1-pro-preview' },
          { label: 'Gemini 3 Flash', value: 'gemini-3-flash-preview' },
          { label: 'Gemini 3.1 Flash Lite', value: 'gemini-3.1-flash-lite-preview' },
          { label: 'Gemini 2.5 Pro', value: 'gemini-2.5-pro' },
          { label: 'Gemini 2.5 Flash', value: 'gemini-2.5-flash' },
          { label: 'Gemini 2.5 Flash Lite', value: 'gemini-2.5-flash-lite' },
        ],
      },
      {
        key: 'max_tokens',
        label: 'Max Tokens',
        type: 'integer',
        required: false,
        default: 8192,
        min: 1,
        max: 65535,
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'float',
        required: false,
        default: 1,
        min: 0,
        max: 2,
        step: 0.1,
      },
      {
        key: 'thinkingLevel',
        label: 'Thinking Level',
        type: 'enum',
        required: false,
        default: '',
        options: [
          { label: 'Default', value: '' },
          { label: 'Minimal', value: 'minimal' },
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
        ],
      },
      {
        key: 'thinkingBudget',
        label: 'Thinking Budget (2.5 only)',
        type: 'integer',
        required: false,
        placeholder: 'For Gemini 2.5 models only',
        min: 0,
        max: 65536,
      },
      {
        key: 'top_p',
        label: 'Top P',
        type: 'float',
        required: false,
        min: 0,
        max: 1,
        step: 0.05,
        placeholder: 'Default',
      },
      {
        key: 'top_k',
        label: 'Top K',
        type: 'integer',
        required: false,
        placeholder: '64',
      },
      {
        key: 'stop_sequences',
        label: 'Stop Sequences',
        type: 'string',
        required: false,
        placeholder: 'Comma-separated',
      },
      {
        key: 'response_format',
        label: 'Response Format',
        type: 'enum',
        required: false,
        default: 'text/plain',
        options: [
          { label: 'Text', value: 'text/plain' },
          { label: 'JSON', value: 'application/json' },
        ],
      },
    ],
  },

  'imagen-4-generate': {
    id: 'imagen-4-generate',
    displayName: 'Imagen 4',
    category: 'image-gen',
    apiProvider: 'google',
    apiEndpoint: '/v1beta/models/{model}:generateImages',
    envKeyName: 'GOOGLE_API_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'imagen-4.0-generate-001',
        options: [
          { label: 'Imagen 4', value: 'imagen-4.0-generate-001' },
          { label: 'Imagen 4 Ultra', value: 'imagen-4.0-ultra-generate-001' },
          { label: 'Imagen 4 Fast', value: 'imagen-4.0-fast-generate-001' },
        ],
      },
      {
        key: 'aspectRatio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '1:1',
        options: [
          { label: '1:1', value: '1:1' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
        ],
      },
      {
        key: 'numberOfImages',
        label: 'Count',
        type: 'integer',
        required: false,
        default: 1,
        min: 1,
        max: 4,
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
      {
        key: 'enhancePrompt',
        label: 'Enhance Prompt',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'personGeneration',
        label: 'Person Generation',
        type: 'enum',
        required: false,
        default: 'allow_adult',
        options: [
          { label: 'Allow All', value: 'allow_all' },
          { label: 'Allow Adult', value: 'allow_adult' },
          { label: "Don't Allow", value: 'dont_allow' },
        ],
      },
    ],
  },

  'kling-v2-1': {
    id: 'kling-v2-1',
    displayName: 'Kling v2.1',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/kling-video/v2.1/pro/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5',
        options: [
          { label: '5 seconds', value: '5' },
          { label: '10 seconds', value: '10' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
        ],
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        default: 'blur, distort, and low quality',
      },
      {
        key: 'cfg_scale',
        label: 'CFG Scale',
        type: 'float',
        required: false,
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
  },

  'sora-2': {
    id: 'sora-2',
    displayName: 'Sora 2',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/sora-2/text-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080p',
        options: [
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration (s)',
        type: 'enum',
        required: false,
        default: 4,
        options: [
          { label: '4s', value: 4 },
          { label: '8s', value: 8 },
          { label: '12s', value: 12 },
          { label: '16s', value: 16 },
          { label: '20s', value: 20 },
        ],
      },
    ],
  },

  'nano-banana': {
    id: 'nano-banana',
    displayName: 'Nano Banana',
    category: 'image-gen',
    apiProvider: 'google',
    apiEndpoint: '/v1beta/models/{model}:generateContent',
    envKeyName: 'GOOGLE_API_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'images', label: 'Images', dataType: 'Image', required: false, multiple: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: false,
        default: 'gemini-2.5-flash-image',
        options: [
          { label: 'Gemini 3 Pro Image', value: 'gemini-3-pro-image-preview' },
          { label: 'Gemini 3.1 Flash Image', value: 'gemini-3.1-flash-image-preview' },
          { label: 'Gemini 2.5 Flash Image', value: 'gemini-2.5-flash-image' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '1:1',
        options: [
          { label: '1:1', value: '1:1' },
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
        ],
      },
    ],
  },

  'veo-3': {
    id: 'veo-3',
    displayName: 'Veo 3.1',
    category: 'video-gen',
    apiProvider: 'google',
    apiEndpoint: 'veo-3.1-generate-preview',
    envKeyName: ['GOOGLE_API_KEY', 'FAL_KEY'],
    executionPattern: 'async-poll',
    directKeyName: 'GOOGLE_API_KEY',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'First Frame', dataType: 'Image', required: false },
      { id: 'last_frame', label: 'Last Frame', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [],
    sharedParams: [
      {
        key: 'aspectRatio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '8',
        options: [
          { label: '4 seconds', value: '4' },
          { label: '6 seconds', value: '6' },
          { label: '8 seconds', value: '8' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
    ],
    directParams: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: false,
        default: 'veo-3.1-generate-preview',
        options: [
          { label: 'Veo 3.1', value: 'veo-3.1-generate-preview' },
          { label: 'Veo 3.1 Lite', value: 'veo-3.1-lite-generate-preview' },
          { label: 'Veo 3.1 Fast', value: 'veo-3.1-fast-generate-preview' },
          { label: 'Veo 3', value: 'veo-3-generate-001' },
          { label: 'Veo 2', value: 'veo-2-generate-001' },
        ],
      },
    ],
    falParams: [
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        placeholder: 'What to avoid',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
      {
        key: 'safety_tolerance',
        label: 'Safety Tolerance',
        type: 'enum',
        required: false,
        default: '4',
        options: [
          { label: '1 (Strict)', value: '1' },
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
          { label: '5', value: '5' },
          { label: '6 (Permissive)', value: '6' },
        ],
      },
    ],
  },

  'flux-schnell': {
    id: 'flux-schnell',
    displayName: 'FLUX Schnell',
    category: 'image-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/flux/schnell',
    envKeyName: 'FAL_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '1:1', value: '1:1' },
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
        ],
      },
      {
        key: 'num_images',
        label: 'Count',
        type: 'integer',
        required: false,
        default: 1,
        min: 1,
        max: 4,
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        default: undefined,
        min: 0,
        max: 2147483647,
      },
    ],
  },

  'fast-sdxl': {
    id: 'fast-sdxl',
    displayName: 'Fast SDXL',
    category: 'image-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/fast-sdxl',
    envKeyName: 'FAL_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'image_size',
        label: 'Image Size',
        type: 'enum',
        required: false,
        default: 'square_hd',
        options: [
          { label: 'Square HD', value: 'square_hd' },
          { label: 'Square', value: 'square' },
          { label: 'Landscape 4:3', value: 'landscape_4_3' },
          { label: 'Landscape 16:9', value: 'landscape_16_9' },
          { label: 'Portrait 4:3', value: 'portrait_4_3' },
          { label: 'Portrait 16:9', value: 'portrait_16_9' },
        ],
      },
      {
        key: 'num_images',
        label: 'Count',
        type: 'integer',
        required: false,
        default: 1,
        min: 1,
        max: 4,
      },
      {
        key: 'guidance_scale',
        label: 'Guidance Scale',
        type: 'float',
        required: false,
        default: 7.5,
        min: 1,
        max: 20,
        step: 0.5,
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        default: '',
        placeholder: 'What to avoid in the image...',
      },
    ],
  },

  'wan-2-6-t2v': {
    id: 'wan-2-6-t2v',
    displayName: 'Wan 2.6 T2V',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'wan/v2.6/text-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '10 seconds', value: '10s' },
          { label: '15 seconds', value: '15s' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
        ],
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        placeholder: 'What to avoid',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
      {
        key: 'generate_audio',
        label: 'Generate Audio',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
  },

  'luma-ray2-t2v': {
    id: 'luma-ray2-t2v',
    displayName: 'Luma Ray 2',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/luma-dream-machine/ray-2',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '1:1', value: '1:1' },
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '9 seconds', value: '9s' },
        ],
      },
      {
        key: 'loop',
        label: 'Seamless Loop',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '540p', value: '540p' },
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
    ],
  },

  'ltx-video-2': {
    id: 'ltx-video-2',
    displayName: 'LTX Video 2',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/ltx-2/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '6',
        options: [
          { label: '6 seconds', value: '6' },
          { label: '8 seconds', value: '8' },
          { label: '10 seconds', value: '10' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080p',
        options: [
          { label: '1080p', value: '1080p' },
          { label: '1440p', value: '1440p' },
          { label: '2160p', value: '2160p' },
        ],
      },
    ],
  },

  'meshy-text-to-3d': {
    id: 'meshy-text-to-3d',
    displayName: 'Meshy 6 Text-to-3D',
    category: '3d-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/meshy/v6/text-to-3d',
    envKeyName: ['MESHY_API_KEY', 'FAL_KEY'],
    executionPattern: 'async-poll',
    directKeyName: 'MESHY_API_KEY',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'mesh', label: 'Mesh', dataType: 'Mesh', required: false },
    ],
    params: [],
    sharedParams: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'enum',
        required: false,
        default: 'full',
        options: [
          { label: 'Preview', value: 'preview' },
          { label: 'Full', value: 'full' },
        ],
      },
      {
        key: 'topology',
        label: 'Topology',
        type: 'enum',
        required: false,
        default: 'triangle',
        options: [
          { label: 'Triangle', value: 'triangle' },
          { label: 'Quad', value: 'quad' },
        ],
      },
      {
        key: 'target_polycount',
        label: 'Polycount',
        type: 'integer',
        required: false,
        default: 30000,
        min: 1000,
        max: 200000,
      },
      {
        key: 'symmetry_mode',
        label: 'Symmetry',
        type: 'enum',
        required: false,
        default: 'auto',
        options: [
          { label: 'Off', value: 'off' },
          { label: 'Auto', value: 'auto' },
          { label: 'On', value: 'on' },
        ],
      },
      {
        key: 'enable_pbr',
        label: 'PBR Materials',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'pose_mode',
        label: 'Pose Mode',
        type: 'enum',
        required: false,
        default: '',
        options: [
          { label: 'None', value: '' },
          { label: 'A-Pose', value: 'a-pose' },
          { label: 'T-Pose', value: 't-pose' },
        ],
      },
      {
        key: 'enable_rigging',
        label: 'Rigging',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
    directParams: [
      {
        key: 'ai_model',
        label: 'AI Model',
        type: 'enum',
        required: false,
        default: 'latest',
        options: [
          { label: 'Latest (Meshy 6)', value: 'latest' },
          { label: 'Meshy 6', value: 'meshy-6' },
          { label: 'Meshy 5', value: 'meshy-5' },
        ],
      },
      {
        key: 'target_formats',
        label: 'Output Formats',
        type: 'string',
        required: false,
        default: 'glb',
        placeholder: 'glb,fbx,obj,usdz',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
    ],
    falParams: [
      {
        key: 'texture_prompt',
        label: 'Texture Prompt',
        type: 'string',
        required: false,
        placeholder: 'Guide the texturing process',
      },
      {
        key: 'enable_prompt_expansion',
        label: 'Enhance Prompt',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'enable_safety_checker',
        label: 'Safety Checker',
        type: 'boolean',
        required: false,
        default: true,
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
    ],
  },

  'meshy-image-to-3d': {
    id: 'meshy-image-to-3d',
    displayName: 'Meshy 6 Image-to-3D',
    category: '3d-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/meshy/v6/image-to-3d',
    envKeyName: ['MESHY_API_KEY', 'FAL_KEY'],
    executionPattern: 'async-poll',
    directKeyName: 'MESHY_API_KEY',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
    ],
    outputPorts: [
      { id: 'mesh', label: 'Mesh', dataType: 'Mesh', required: false },
    ],
    params: [],
    sharedParams: [
      {
        key: 'topology',
        label: 'Topology',
        type: 'enum',
        required: false,
        default: 'triangle',
        options: [
          { label: 'Triangle', value: 'triangle' },
          { label: 'Quad', value: 'quad' },
        ],
      },
      {
        key: 'target_polycount',
        label: 'Polycount',
        type: 'integer',
        required: false,
        default: 30000,
        min: 1000,
        max: 200000,
      },
      {
        key: 'symmetry_mode',
        label: 'Symmetry',
        type: 'enum',
        required: false,
        default: 'auto',
        options: [
          { label: 'Off', value: 'off' },
          { label: 'Auto', value: 'auto' },
          { label: 'On', value: 'on' },
        ],
      },
      {
        key: 'should_texture',
        label: 'Texture',
        type: 'boolean',
        required: false,
        default: true,
      },
      {
        key: 'enable_pbr',
        label: 'PBR Materials',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'pose_mode',
        label: 'Pose Mode',
        type: 'enum',
        required: false,
        default: '',
        options: [
          { label: 'None', value: '' },
          { label: 'A-Pose', value: 'a-pose' },
          { label: 'T-Pose', value: 't-pose' },
        ],
      },
      {
        key: 'enable_rigging',
        label: 'Rigging',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
    directParams: [
      {
        key: 'ai_model',
        label: 'AI Model',
        type: 'enum',
        required: false,
        default: 'latest',
        options: [
          { label: 'Latest (Meshy 6)', value: 'latest' },
          { label: 'Meshy 6', value: 'meshy-6' },
          { label: 'Meshy 5', value: 'meshy-5' },
        ],
      },
      {
        key: 'model_type',
        label: 'Mesh Type',
        type: 'enum',
        required: false,
        default: 'standard',
        options: [
          { label: 'Standard', value: 'standard' },
          { label: 'Low Poly', value: 'lowpoly' },
        ],
      },
      {
        key: 'target_formats',
        label: 'Output Formats',
        type: 'string',
        required: false,
        default: 'glb',
        placeholder: 'glb,fbx,obj,usdz',
      },
    ],
    falParams: [
      {
        key: 'texture_prompt',
        label: 'Texture Prompt',
        type: 'string',
        required: false,
        placeholder: 'Guide the texturing process',
      },
      {
        key: 'enable_safety_checker',
        label: 'Safety Checker',
        type: 'boolean',
        required: false,
        default: true,
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
    ],
  },

  'hunyuan3d-text-to-3d': {
    id: 'hunyuan3d-text-to-3d',
    displayName: 'Hunyuan3D V3 Text-to-3D',
    category: '3d-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/hunyuan3d-v3/text-to-3d',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'mesh', label: 'Mesh', dataType: 'Mesh', required: false },
    ],
    params: [
      {
        key: 'generate_type',
        label: 'Quality',
        type: 'enum',
        required: false,
        default: 'Normal',
        options: [
          { label: 'Normal', value: 'Normal' },
          { label: 'Low Poly', value: 'LowPoly' },
          { label: 'Geometry Only', value: 'Geometry' },
        ],
      },
      {
        key: 'face_count',
        label: 'Face Count',
        type: 'integer',
        required: false,
        default: 500000,
        min: 40000,
        max: 1500000,
      },
      {
        key: 'enable_pbr',
        label: 'PBR Materials',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'polygon_type',
        label: 'Polygon Type',
        type: 'enum',
        required: false,
        default: 'triangle',
        options: [
          { label: 'Triangle', value: 'triangle' },
          { label: 'Quadrilateral', value: 'quadrilateral' },
        ],
      },
    ],
  },

  'hunyuan3d-image-to-3d': {
    id: 'hunyuan3d-image-to-3d',
    displayName: 'Hunyuan3D V3 Image-to-3D',
    category: '3d-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/hunyuan3d-v3/image-to-3d',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'front_image', label: 'Front Image', dataType: 'Image', required: true },
      { id: 'back_image', label: 'Back Image', dataType: 'Image', required: false },
      { id: 'left_image', label: 'Left Image', dataType: 'Image', required: false },
      { id: 'right_image', label: 'Right Image', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'mesh', label: 'Mesh', dataType: 'Mesh', required: false },
    ],
    params: [
      {
        key: 'generate_type',
        label: 'Quality',
        type: 'enum',
        required: false,
        default: 'Normal',
        options: [
          { label: 'Normal', value: 'Normal' },
          { label: 'Low Poly', value: 'LowPoly' },
          { label: 'Geometry Only', value: 'Geometry' },
        ],
      },
      {
        key: 'face_count',
        label: 'Face Count',
        type: 'integer',
        required: false,
        default: 500000,
        min: 40000,
        max: 1500000,
      },
      {
        key: 'enable_pbr',
        label: 'PBR Materials',
        type: 'boolean',
        required: false,
        default: false,
      },
      {
        key: 'polygon_type',
        label: 'Polygon Type',
        type: 'enum',
        required: false,
        default: 'triangle',
        options: [
          { label: 'Triangle', value: 'triangle' },
          { label: 'Quadrilateral', value: 'quadrilateral' },
        ],
      },
    ],
  },

  'gpt-image-1-edit': {
    id: 'gpt-image-1-edit',
    displayName: 'GPT Image 1 Edit',
    category: 'image-gen',
    apiProvider: 'openai',
    apiEndpoint: '/v1/images/edits',
    envKeyName: 'OPENAI_API_KEY',
    executionPattern: 'sync',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'mask', label: 'Mask', dataType: 'Mask', required: false },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: true,
        default: 'gpt-image-1',
        options: [
          { label: 'GPT Image 1', value: 'gpt-image-1' },
          { label: 'GPT Image 1.5', value: 'gpt-image-1.5' },
          { label: 'GPT Image 1 Mini', value: 'gpt-image-1-mini' },
          { label: 'DALL-E 2', value: 'dall-e-2' },
        ],
      },
      {
        key: 'n',
        label: 'Count',
        type: 'integer',
        required: false,
        default: 1,
        min: 1,
        max: 10,
      },
      {
        key: 'size',
        label: 'Size',
        type: 'enum',
        required: false,
        default: '1024x1024',
        options: [
          { label: '1024×1024', value: '1024x1024' },
          { label: '1536×1024', value: '1536x1024' },
          { label: '1024×1536', value: '1024x1536' },
        ],
      },
      {
        key: 'quality',
        label: 'Quality',
        type: 'enum',
        required: false,
        default: 'medium',
        options: [
          { label: 'Low', value: 'low' },
          { label: 'Medium', value: 'medium' },
          { label: 'High', value: 'high' },
        ],
      },
      {
        key: 'output_format',
        label: 'Format',
        type: 'enum',
        required: false,
        default: 'png',
        options: [
          { label: 'PNG', value: 'png' },
          { label: 'JPEG', value: 'jpeg' },
          { label: 'WebP', value: 'webp' },
        ],
      },
      {
        key: 'background',
        label: 'Background',
        type: 'enum',
        required: false,
        default: 'auto',
        options: [
          { label: 'Auto', value: 'auto' },
          { label: 'Transparent', value: 'transparent' },
          { label: 'Opaque', value: 'opaque' },
        ],
      },
    ],
  },

  'remove-background': {
    id: 'remove-background',
    displayName: 'Remove Background',
    category: 'transform',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/imageutils/rembg',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [],
  },

  'recraft-v4-raster': {
    id: 'recraft-v4-raster',
    displayName: 'Recraft V4',
    category: 'image-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/recraft/v4/text-to-image',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'image_size',
        label: 'Size',
        type: 'enum',
        required: false,
        default: 'square_hd',
        options: [
          { label: 'Square HD', value: 'square_hd' },
          { label: 'Square', value: 'square' },
          { label: 'Portrait 4:3', value: 'portrait_4_3' },
          { label: 'Portrait 16:9', value: 'portrait_16_9' },
          { label: 'Landscape 4:3', value: 'landscape_4_3' },
          { label: 'Landscape 16:9', value: 'landscape_16_9' },
        ],
      },
      {
        key: 'style',
        label: 'Style',
        type: 'enum',
        required: false,
        default: 'realistic_image',
        options: [
          { label: 'Realistic', value: 'realistic_image' },
          { label: 'Digital Illustration', value: 'digital_illustration' },
          { label: 'Vector Illustration', value: 'vector_illustration' },
          { label: 'Icon', value: 'icon' },
        ],
      },
      {
        key: 'style_id',
        label: 'Style ID',
        type: 'string',
        required: false,
        placeholder: 'Custom style UUID',
      },
      {
        key: 'colors',
        label: 'Color Palette',
        type: 'string',
        required: false,
        placeholder: '#FF0000,#00FF00,#0000FF',
      },
    ],
  },

  'recraft-v4-svg': {
    id: 'recraft-v4-svg',
    displayName: 'Recraft V4 SVG',
    category: 'image-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/recraft/v4/text-to-vector',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'svg', label: 'SVG', dataType: 'SVG', required: false },
    ],
    params: [
      {
        key: 'image_size',
        label: 'Size',
        type: 'enum',
        required: false,
        default: 'square_hd',
        options: [
          { label: 'Square HD', value: 'square_hd' },
          { label: 'Square', value: 'square' },
          { label: 'Portrait 4:3', value: 'portrait_4_3' },
          { label: 'Portrait 16:9', value: 'portrait_16_9' },
          { label: 'Landscape 4:3', value: 'landscape_4_3' },
          { label: 'Landscape 16:9', value: 'landscape_16_9' },
        ],
      },
      {
        key: 'style',
        label: 'Style',
        type: 'enum',
        required: false,
        default: 'vector_illustration',
        options: [
          { label: 'Vector Illustration', value: 'vector_illustration' },
          { label: 'Digital Illustration', value: 'digital_illustration' },
          { label: 'Icon', value: 'icon' },
        ],
      },
      {
        key: 'style_id',
        label: 'Style ID',
        type: 'string',
        required: false,
        placeholder: 'Custom style UUID',
      },
      {
        key: 'colors',
        label: 'Color Palette',
        type: 'string',
        required: false,
        placeholder: '#FF0000,#00FF00,#0000FF',
      },
    ],
  },

  'minimax-t2v': {
    id: 'minimax-t2v',
    displayName: 'MiniMax T2V',
    category: 'video-gen',
    apiProvider: 'minimax',
    apiEndpoint: 'https://api.minimaxi.chat/v1/video_generation',
    envKeyName: 'MINIMAX_API_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: false,
        default: 'MiniMax-Hailuo-2.3',
        options: [
          { label: 'Hailuo 2.3', value: 'MiniMax-Hailuo-2.3' },
          { label: 'Hailuo 02', value: 'MiniMax-Hailuo-02' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: 6,
        options: [
          { label: '6 seconds', value: 6 },
          { label: '9 seconds', value: 9 },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080P',
        options: [
          { label: '720P', value: '720P' },
          { label: '1080P', value: '1080P' },
        ],
      },
    ],
  },

  'minimax-i2v': {
    id: 'minimax-i2v',
    displayName: 'MiniMax I2V',
    category: 'video-gen',
    apiProvider: 'minimax',
    apiEndpoint: 'https://api.minimaxi.chat/v1/video_generation',
    envKeyName: 'MINIMAX_API_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'First Frame', dataType: 'Image', required: true },
      { id: 'last_frame', label: 'Last Frame', dataType: 'Image', required: false },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: false,
        default: 'MiniMax-Hailuo-2.3',
        options: [
          { label: 'Hailuo 2.3', value: 'MiniMax-Hailuo-2.3' },
          { label: 'Hailuo 02', value: 'MiniMax-Hailuo-02' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: 6,
        options: [
          { label: '6 seconds', value: 6 },
          { label: '9 seconds', value: 9 },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080P',
        options: [
          { label: '720P', value: '720P' },
          { label: '1080P', value: '1080P' },
        ],
      },
    ],
  },

  'minimax-s2v': {
    id: 'minimax-s2v',
    displayName: 'MiniMax S2V',
    category: 'video-gen',
    apiProvider: 'minimax',
    apiEndpoint: 'https://api.minimaxi.chat/v1/video_generation',
    envKeyName: 'MINIMAX_API_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Character Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: 6,
        options: [
          { label: '6 seconds', value: 6 },
          { label: '9 seconds', value: 9 },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080P',
        options: [
          { label: '720P', value: '720P' },
          { label: '1080P', value: '1080P' },
        ],
      },
    ],
  },

  'kling-v3': {
    id: 'kling-v3',
    displayName: 'Kling V3',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/kling-video/v3/standard/text-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'Start Image', dataType: 'Image', required: false },
      { id: 'end_image', label: 'End Image', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5',
        options: [
          { label: '3 seconds', value: '3' },
          { label: '5 seconds', value: '5' },
          { label: '10 seconds', value: '10' },
          { label: '15 seconds', value: '15' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080p',
        options: [
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
        ],
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        placeholder: 'What to avoid',
      },
      {
        key: 'generate_audio',
        label: 'Generate Audio',
        type: 'boolean',
        required: false,
        default: true,
      },
      {
        key: 'cfg_scale',
        label: 'CFG Scale',
        type: 'float',
        required: false,
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
  },

  'luma-ray2-i2v': {
    id: 'luma-ray2-i2v',
    displayName: 'Luma Ray 2 I2V',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/luma-dream-machine/ray-2/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'end_image', label: 'End Image', dataType: 'Image', required: false },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
          { label: '21:9', value: '21:9' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '540p',
        options: [
          { label: '540p', value: '540p' },
          { label: '720p (2x cost)', value: '720p' },
          { label: '1080p (4x cost)', value: '1080p' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '9 seconds', value: '9s' },
        ],
      },
      {
        key: 'loop',
        label: 'Seamless Loop',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
  },

  'wan-2-6-i2v': {
    id: 'wan-2-6-i2v',
    displayName: 'Wan 2.6 I2V',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/wan/v2.6/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '10 seconds', value: '10s' },
          { label: '15 seconds', value: '15s' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '480p', value: '480p' },
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
        ],
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        placeholder: 'What to avoid',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
      {
        key: 'generate_audio',
        label: 'Generate Audio',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
  },
  'video-input': {
    id: 'video-input',
    displayName: 'Video Input',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'filePath',
        label: 'File',
        type: 'file',
        required: true,
        default: '',
      },
    ],
  },
  'audio-input': {
    id: 'audio-input',
    displayName: 'Audio Input',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [],
    outputPorts: [
      { id: 'audio', label: 'Audio', dataType: 'Audio', required: false },
    ],
    params: [
      {
        key: 'filePath',
        label: 'File',
        type: 'file',
        required: true,
        default: '',
      },
    ],
  },
  'sticky-note': {
    id: 'sticky-note',
    displayName: 'Sticky Note',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [],
    outputPorts: [],
    params: [
      {
        key: 'content',
        label: 'Note',
        type: 'textarea',
        required: false,
        default: '',
        placeholder: 'Add a note...',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'enum',
        required: false,
        default: 'yellow',
        options: [
          { label: 'Yellow', value: 'yellow' },
          { label: 'Blue', value: 'blue' },
          { label: 'Green', value: 'green' },
          { label: 'Pink', value: 'pink' },
          { label: 'Grey', value: 'grey' },
        ],
      },
    ],
  },
  'luma-ray2-flash-modify': {
    id: 'luma-ray2-flash-modify',
    displayName: 'Luma Ray 2 Flash Modify',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/luma-dream-machine/ray-2-flash/modify',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
          { label: '21:9', value: '21:9' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '540p',
        options: [
          { label: '540p', value: '540p' },
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '9 seconds', value: '9s' },
        ],
      },
    ],
  },
  'wan-2-6-r2v': {
    id: 'wan-2-6-r2v',
    displayName: 'Wan 2.6 R2V',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/wan/v2.6/reference-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'video1', label: 'Video 1', dataType: 'Video', required: true },
      { id: 'video2', label: 'Video 2', dataType: 'Video', required: false },
      { id: 'video3', label: 'Video 3', dataType: 'Video', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '10 seconds', value: '10s' },
          { label: '15 seconds', value: '15s' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '480p', value: '480p' },
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
        ],
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        placeholder: 'What to avoid',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
    ],
  },
  'pixverse-v4-5': {
    id: 'pixverse-v4-5',
    displayName: 'PixVerse V4.5',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/pixverse/v4.5/text-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: 5,
        options: [
          { label: '5 seconds', value: 5 },
          { label: '8 seconds', value: 8 },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '360p', value: '360p' },
          { label: '540p', value: '540p' },
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'quality',
        label: 'Quality',
        type: 'enum',
        required: false,
        default: 'Normal',
        options: [
          { label: 'Turbo', value: 'Turbo' },
          { label: 'Normal', value: 'Normal' },
          { label: 'Fast', value: 'Fast' },
        ],
      },
      {
        key: 'negative_prompt',
        label: 'Negative Prompt',
        type: 'string',
        required: false,
        placeholder: 'What to avoid',
      },
      {
        key: 'seed',
        label: 'Seed',
        type: 'integer',
        required: false,
        placeholder: 'Random',
      },
    ],
  },
  'seedance-v1-5': {
    id: 'seedance-v1-5',
    displayName: 'Seedance V1.5',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/seedance/v1.5/text-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '8s',
        options: [
          { label: '4 seconds', value: '4s' },
          { label: '6 seconds', value: '6s' },
          { label: '8 seconds', value: '8s' },
          { label: '10 seconds', value: '10s' },
          { label: '12 seconds', value: '12s' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
          { label: '21:9', value: '21:9' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '720p',
        options: [
          { label: '480p', value: '480p' },
          { label: '720p', value: '720p' },
        ],
      },
    ],
  },
  'moonvalley': {
    id: 'moonvalley',
    displayName: 'Moonvalley',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/moonvalley/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5s',
        options: [
          { label: '5 seconds', value: '5s' },
          { label: '10 seconds', value: '10s' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1920x1080',
        options: [
          { label: '1920x1080', value: '1920x1080' },
          { label: '1080x1920', value: '1080x1920' },
          { label: '1152x1152', value: '1152x1152' },
        ],
      },
    ],
  },
  'kling-o3': {
    id: 'kling-o3',
    displayName: 'Kling Omni 3',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/kling-video/o3/standard/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: true },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'ref_video1', label: 'Ref Video 1', dataType: 'Video', required: false },
      { id: 'ref_video2', label: 'Ref Video 2', dataType: 'Video', required: false },
      { id: 'ref_video3', label: 'Ref Video 3', dataType: 'Video', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'enum',
        required: false,
        default: '5',
        options: [
          { label: '5 seconds', value: '5' },
          { label: '10 seconds', value: '10' },
        ],
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080p',
        options: [
          { label: '720p', value: '720p' },
          { label: '1080p', value: '1080p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
        ],
      },
      {
        key: 'generate_audio',
        label: 'Generate Audio',
        type: 'boolean',
        required: false,
        default: true,
      },
    ],
  },
  'ltx-2-3': {
    id: 'ltx-2-3',
    displayName: 'LTX 2.3',
    category: 'video-gen',
    apiProvider: 'fal',
    apiEndpoint: 'fal-ai/ltx-2.3/image-to-video',
    envKeyName: 'FAL_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'audio', label: 'Audio', dataType: 'Audio', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'integer',
        required: false,
        default: 6,
        min: 2,
        max: 20,
      },
      {
        key: 'resolution',
        label: 'Resolution',
        type: 'enum',
        required: false,
        default: '1080p',
        options: [
          { label: '1080p', value: '1080p' },
          { label: '1440p', value: '1440p' },
          { label: '2160p', value: '2160p' },
        ],
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
        ],
      },
      {
        key: 'fps',
        label: 'FPS',
        type: 'enum',
        required: false,
        default: 25,
        options: [
          { label: '25', value: 25 },
          { label: '50', value: 50 },
        ],
      },
      {
        key: 'generate_audio',
        label: 'Generate Audio',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
  },

  'frame-extractor': {
    id: 'frame-extractor',
    displayName: 'Frame Extractor',
    category: 'transform',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'enum',
        required: false,
        default: 'first_frame',
        options: [
          { label: 'First Frame', value: 'first_frame' },
          { label: 'Last Frame', value: 'last_frame' },
          { label: 'Middle Frame', value: 'middle_frame' },
          { label: 'At Timestamp', value: 'timestamp' },
        ],
      },
      {
        key: 'timestamp',
        label: 'Timestamp (s)',
        type: 'float',
        required: false,
        default: 0,
        min: 0,
        step: 0.1,
        placeholder: '0.0',
      },
    ],
  },

  'array-builder': {
    id: 'array-builder',
    displayName: 'Array Builder',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'item1', label: 'Item 1', dataType: 'Any', required: true },
      { id: 'item2', label: 'Item 2', dataType: 'Any', required: false },
      { id: 'item3', label: 'Item 3', dataType: 'Any', required: false },
      { id: 'item4', label: 'Item 4', dataType: 'Any', required: false },
      { id: 'item5', label: 'Item 5', dataType: 'Any', required: false },
      { id: 'item6', label: 'Item 6', dataType: 'Any', required: false },
      { id: 'item7', label: 'Item 7', dataType: 'Any', required: false },
      { id: 'item8', label: 'Item 8', dataType: 'Any', required: false },
    ],
    outputPorts: [
      { id: 'array', label: 'Array', dataType: 'Array', required: false },
    ],
    params: [],
  },

  'array-selector': {
    id: 'array-selector',
    displayName: 'Array Selector',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'array', label: 'Array', dataType: 'Array', required: true },
    ],
    outputPorts: [
      { id: 'item', label: 'Item', dataType: 'Any', required: false },
    ],
    params: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'enum',
        required: false,
        default: 'first',
        options: [
          { label: 'First', value: 'first' },
          { label: 'Last', value: 'last' },
          { label: 'Random', value: 'random' },
          { label: 'By Index', value: 'index' },
        ],
      },
      {
        key: 'index',
        label: 'Index',
        type: 'integer',
        required: false,
        default: 0,
        min: 0,
      },
    ],
  },

  'image-compare': {
    id: 'image-compare',
    displayName: 'Image Compare',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'imageA', label: 'Image A', dataType: 'Image', required: true },
      { id: 'imageB', label: 'Image B', dataType: 'Image', required: true },
    ],
    outputPorts: [],
    params: [],
  },

  'grok-imagine-video': {
    id: 'grok-imagine-video',
    displayName: 'Grok Imagine Video',
    category: 'video-gen',
    apiProvider: 'xai',
    apiEndpoint: 'https://api.x.ai/v1/images/generations',
    envKeyName: 'XAI_API_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'integer',
        required: false,
        default: 5,
        min: 1,
        max: 15,
      },
      {
        key: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'enum',
        required: false,
        default: '16:9',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '9:16', value: '9:16' },
          { label: '1:1', value: '1:1' },
          { label: '4:3', value: '4:3' },
          { label: '3:4', value: '3:4' },
        ],
      },
    ],
  },

  'higgsfield': {
    id: 'higgsfield',
    displayName: 'Higgsfield',
    category: 'video-gen',
    apiProvider: 'higgsfield',
    apiEndpoint: 'https://api.higgsfield.ai/v1/video/generate',
    envKeyName: 'HIGGSFIELD_API_KEY',
    executionPattern: 'async-poll',
    inputPorts: [
      { id: 'prompt', label: 'Prompt', dataType: 'Text', required: true },
    ],
    outputPorts: [
      { id: 'video', label: 'Video', dataType: 'Video', required: false },
    ],
    params: [
      {
        key: 'model',
        label: 'Model',
        type: 'enum',
        required: false,
        default: 'higgsfield-native',
        options: [
          { label: 'Higgsfield Native', value: 'higgsfield-native' },
          { label: 'Kling 2.6', value: 'kling-2.6' },
          { label: 'Sora 2', value: 'sora-2' },
          { label: 'Veo 3.1', value: 'veo-3.1' },
        ],
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'integer',
        required: false,
        default: 5,
        min: 1,
        max: 15,
      },
    ],
  },

  'svg-rasterize': {
    id: 'svg-rasterize',
    displayName: 'SVG Rasterize',
    category: 'transform',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'svg', label: 'SVG', dataType: 'SVG', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'width',
        label: 'Width',
        type: 'integer',
        required: false,
        default: 1024,
        min: 64,
        max: 4096,
      },
      {
        key: 'height',
        label: 'Height',
        type: 'integer',
        required: false,
        default: 1024,
        min: 64,
        max: 4096,
      },
      {
        key: 'background',
        label: 'Background',
        type: 'enum',
        required: false,
        default: 'transparent',
        options: [
          { label: 'Transparent', value: 'transparent' },
          { label: 'White', value: 'white' },
        ],
      },
    ],
  },

  'iterator-image': {
    id: 'iterator-image',
    displayName: 'Image Iterator',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'array', label: 'Images', dataType: 'Array', required: true },
    ],
    outputPorts: [
      { id: 'image', label: 'Image', dataType: 'Image', required: false },
    ],
    params: [
      {
        key: 'batch_size_cap',
        label: 'Batch Size Cap',
        type: 'integer',
        required: false,
        default: 10,
        min: 1,
        max: 25,
      },
    ],
  },

  'iterator-text': {
    id: 'iterator-text',
    displayName: 'Text Iterator',
    category: 'utility',
    apiProvider: 'openai',
    apiEndpoint: '',
    envKeyName: [],
    executionPattern: 'sync',
    inputPorts: [
      { id: 'array', label: 'Texts', dataType: 'Array', required: true },
    ],
    outputPorts: [
      { id: 'text', label: 'Text', dataType: 'Text', required: false },
    ],
    params: [
      {
        key: 'batch_size_cap',
        label: 'Batch Size Cap',
        type: 'integer',
        required: false,
        default: 10,
        min: 1,
        max: 25,
      },
    ],
  },
};

export function getNodeDefinition(definitionId: string): ModelNodeDefinition | undefined {
  return NODE_DEFINITIONS[definitionId];
}

export function getNodesByCategory(): Record<string, ModelNodeDefinition[]> {
  const grouped: Record<string, ModelNodeDefinition[]> = {};
  for (const def of Object.values(NODE_DEFINITIONS)) {
    if (!grouped[def.category]) {
      grouped[def.category] = [];
    }
    grouped[def.category].push(def);
  }
  return grouped;
}
